name: EScript
version: ${version}
main: top.e404.escript.EScript
api-version: 1.13
authors: [ 404E ]
depend:
  - Vault
  - PlaceholderAPI
commands:
  escript:
    description: 插件主命令
    aliases:
      - esc
      - es
permissions:
  escript.admin:
    default: op
    description: 允许使用插件指令